# Generated by Django 6.1 on 2026-08-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receiver_name', models.CharField(max_length=150)),
                ('receiver_account', models.CharField(max_length=150)),
                ('bank', models.CharField(max_length=150)),
                ('transaction_type', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=255)),
                ('risk_score', models.IntegerField()),
                ('result', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
