# Generated by Django 6.1 on 2026-08-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recoveryincident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoveryincident',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='recoveryincident',
            name='case_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='recoveryincident',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='recoveryincident',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
