# Generated by Django 6.1 on 2026-08-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_recoveryincident_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryincident',
            name='account_secured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recoveryincident',
            name='bank_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recoveryincident',
            name='evidence_saved',
            field=models.BooleanField(default=False),
        ),
    ]
