# Generated by Django 6.1 on 2026-08-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recoveryincident_account_secured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryincident',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='recovery_evidence/'),
        ),
    ]
